-- Create a table to store the entire JSON state for each user
create table user_data (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id)
);

-- Turn on Row Level Security (RLS)
alter table user_data enable row level security;

-- Policy: Users can only see their own data
create policy "Users can view their own data" on user_data
  for select using (auth.uid() = user_id);

-- Policy: Users can update their own data
create policy "Users can update their own data" on user_data
  for insert with check (auth.uid() = user_id);

create policy "Users can update own data" on user_data
  for update using (auth.uid() = user_id);
